<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_download.test_prepare_pdf-20251016102851" tests="2" file="test_download.py" time="7.052" timestamp="2025-10-16T10:28:58" failures="2" errors="0" skipped="0">
	<testcase classname="test_download.test_prepare_pdf" name="test_load_and_filter" time="7.051" timestamp="2025-10-16T10:28:58" file="test_download.py" line="28">
		<failure type="AssertionError" message="(&lt;class 'PermissionError'&gt;, &lt;class 'OSError'&gt;, &lt;class 'Exception'&gt;) not raised"><![CDATA[Traceback (most recent call last):
  File "C:\Users\SPAC-O-1\Projekter\uge-5\PDFDownloader\test_download.py", line 32, in test_load_and_filter
    with self.assertRaises(tuple([PermissionError, OSError, Exception])):
AssertionError: (<class 'PermissionError'>, <class 'OSError'>, <class 'Exception'>) not raised
]]></failure>
	</testcase>
	<testcase classname="test_download.test_prepare_pdf" name="test_prepare_and_find" time="0.002" timestamp="2025-10-16T10:28:58" file="test_download.py" line="22">
		<failure type="AssertionError" message="(&lt;class 'PermissionError'&gt;, &lt;class 'OSError'&gt;, &lt;class 'Exception'&gt;) not raised"><![CDATA[Traceback (most recent call last):
  File "C:\Users\SPAC-O-1\Projekter\uge-5\PDFDownloader\test_download.py", line 25, in test_prepare_and_find
    with self.assertRaises(tuple([PermissionError, OSError, Exception])):
AssertionError: (<class 'PermissionError'>, <class 'OSError'>, <class 'Exception'>) not raised
]]></failure>
		<system-out><![CDATA[Error: Permission denied when creating folders - 
Error: OS error during folder creation - 
]]></system-out>
	</testcase>
</testsuite>
